### PR TITLE
feat: added dark mode in gallery section

### LINKED ISSUE #474: Adding dark mode to Gallery section of the website
### Is your feature request related to a problem? Please describe.

Gallery section don't have dark mode available for the users as visible in the screenshot.

### Describe the solution you'd like

I will integrate dark mode to gallery section as well for the comfort of users!!

### Describe alternatives you've considered

_No response_

### Additional context

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Viveksati5143**
## Related Issue

Closes #474 

## Description

Integrated dark mode to gallery section as well for the comfort of users!!

## Screenshots
Screenshot 2023-07-03 195412

https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/100852245/1195e9a8-fea4-4f89-84b6-02157fd8c72d

## Checklist

- [X] My code adheres to the established style guidelines of the project.
- [X] I have included comments in areas that may be difficult to understand.
- [X] My changes have not introduced any new warnings.
- [X] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Viveksati5143** [comment]
Please review & merge it @AshAman999 👋

**Review by AshAman999 — APPROVED** [review]

**Comment by Viveksati5143** [comment]
@AshAman999 level 1?🙂

**Comment by AshAman999** [comment]
> @AshAman999 level 1?🙂

TBH i am not sure , that's i guess should be determined by @SahityaRoy

**Comment by Viveksati5143** [comment]
> > @AshAman999 level 1?🙂
> 
> TBH i am not sure , that's i guess should be determined by @SahityaRoy

Bruh like i'm contributing to other projects so ik it should be level 2.
He won't reply so you only please update it:-(

**Comment by Viveksati5143** [comment]
@AshAman999 As you are a mentor you have a right to do so!!

**Comment by AshAman999** [comment]
Did upgraded your level 
Happy Contributing 👨‍💻

**Pull request merged**
