### PR TITLE
Justify Paragraphs

### PR DESCRIPTION
**Pull request by Nehakanki**
## Related Issue: #392 Justify the paragraphs

Closes #issue_number

## Screenshots

----After------------
image

image
--------After---------
image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Nehakanki** [comment]
@SahityaRoy @AmanKumarAndro @PriyaChandak24 Kindly Merge this PR

**Review by AshAman999 — APPROVED** [review]
LGTM 👍

**Comment by Nehakanki** [comment]
@AshAman999 @SahityaRoy what is this conflicting files indicates?

**Comment by AshAman999** [comment]
> @AshAman999 @SahityaRoy what is this conflicting files indicates?
> 
> 

It's that some more changes were made to that file on the same lines as you have done, and now git gets confused which one to consider your changes or the previous one's.
You need to fix the merge conflicts yourself, manually by keeping the changes from the previous version on top with yours without losing functionality

**Comment by Nehakanki** [comment]
@AshAman999 @SahityaRoy The merge conflict is now resolved kindly merge this PR!

**Pull request merged**
