### PR TITLE
Our initiatives section modified

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have modified the our initiatives section.

https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/132778037/9c44c34c-4bb0-4310-8d31-b19c1387a504

Kindly, review and merge, also ,if you wanna any other changes then please inform me.

### CODE REVIEW

**Comment by SahityaRoy** [comment]
There are too many errors can you please fix the marge conflict?

**Comment by Pragati-3003** [comment]
> There are too many errors can you please fix the marge conflict?

Okie, 
I'll resolve all merge conflicts.

**Comment by Pragati-3003** [comment]
> There are too many errors can you please fix the marge conflict?

I have solved all the merge conflicts kindly review and merge.
and if you wanna any other changes than please inform me.

**Comment by AshAman999** [comment]
again some merge conflicts @Pragati-3003 
please fix this and mention either @SahityaRoy  or me, will merge that so more merge conflicts

**Comment by Pragati-3003** [comment]
> again some merge conflicts @Pragati-3003 please fix this and mention either @SahityaRoy or me, will merge that so more merge conflicts

hey @AshAman999  , @SahityaRoy  I have fixed all the merge conflicts ,please check and merge my PR.

**Review by AshAman999 — APPROVED** [review]
The UI looks great now !

**Comment by AshAman999** [comment]
@Pragati-3003  can you look for the formatting issues, the tests are failing

**Comment by Pragati-3003** [comment]
> @Pragati-3003 can you look for the formatting issues, the tests are failing

I have formatted the code,please check.

**Comment by AshAman999** [comment]
Sorry @Pragati-3003 

can you solve the merge conflicts , and let me know , would make it quick to merge

**Comment by Pragati-3003** [comment]
> Sorry @Pragati-3003
> 
> can you solve the merge conflicts , and let me know , would make it quick to merge

@AshAman999 , i have resolved all the merge conflicts , please check .

**Pull request merged**
