### PR TITLE
fixed the discord link

### LINKED ISSUE #151: The discord link in the readme is expired

### PR DESCRIPTION
**Pull request by yashpreet2707**
closes #151 

https://discord.com/invite/zQXREVf

### CODE REVIEW

**Comment by yashpreet2707** [comment]
hey maintainers, I'm really sorry for my mistake, out of curiosity I have made a PR without the issue being assigned to me. Now I know how this thing works.
So if possible can you please review this PR if you want to merge it please give the [GSSoC'23] tag as well else wise you can close the PR. thanks for hearing me out :-)

**Review by AshAman999 — CHANGES_REQUESTED** [review]
Seems like the link expired yet agian, I think we can better check the validity of the invite link

image

**Comment by AshAman999** [comment]
Hey @yashpreet2707 

did you manage to get a discord invite link for longer duration of time , like one that won't expire in a week?

**Comment by yashpreet2707** [comment]
hey @AshAman999, I did that and the link is working absolutely fine. I think you are still seeing the prev link.

I've added this link - https://discord.gg/mJNqr8nhP7

Please check it again, I've made a new PR named "Updated Discord Link"

**Comment by AshAman999** [comment]
@yashpreet2707 
i mean to say the defualt expiry date for links is 7 days

image

Did you changed that to never expire ?

**Comment by yashpreet2707** [comment]
yes i did, and that link is ->  https://discord.gg/mJNqr8nhP7 (see the PR: *Updated Discord Link* )
Screenshot 2023-06-10 at 6 14 11 PM

**Comment by yashpreet2707** [comment]
https://github.com/yashpreet2707/Eduhub-Community.github.io/commit/eb530f3694f6eb2d100ade3262670015e8cdff3f

**Comment by AshAman999** [comment]
@yashpreet2707 
can you make sure that the latest commits from your branch is on this PR, or better if you can create a seperate PR, cause the changes here are not as same as u are mentioning

**Comment by yashpreet2707** [comment]
hey @AshAman999 ,
please see this PR now -> https://github.com/yashpreet2707/Eduhub-Community.github.io/pull/1

**Pull request closed without merging**
