### PR TITLE
Added `ChatBot`

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
## Description
I have added a Chat Bot for the EduHub Community and here is the Live Video.
It is fun contributing this project and the codebase is maintained 👍🏻 

## Video -
[Screencast from 26-06-23 02:05:23 PM IST.webm](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/121503426/42ca3495-8fa4-4357-a59f-2df99936e5de)

## Screenshots
Screenshot from 2023-06-26 14-04-47

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by SahityaRoy — COMMENTED** [review]
Please resolve the marge conflict

**Comment by SyedImtiyaz-1** [comment]
Hello @SahityaRoy,
It is ready to `Merge` 👍🏻

**Comment by SyedImtiyaz-1** [comment]
> Thanks a lot for your contribution

It's my pleasure

**Comment by SyedImtiyaz-1** [comment]
Logic will be same @killer2O .

> image
> 
> checked with diffcompare for script.js file both the files are same. @gurjeetsinghvirdee you can check for other files


Why you're stalking me IDK.

**Comment by SyedImtiyaz-1** [comment]
@SahityaRoy ,
He is a bot or a spammer please ignore this as you can see he is blocked from GITHUB now, and also it's name changed to Ghost.

### Proof : 

[Uploading Screencast from 02-07-23 05:03:03 PM IST.webm…]()

**Comment by SyedImtiyaz-1** [comment]
@SahityaRoy ,
You can check your chatbot. It's all fine and not same as this spammer @Killer2-O  saying.

**Pull request merged**
