### PR TITLE
fix: Gallery page 

### PR DESCRIPTION
**Pull request by Viveksati5143**
## Related Issue

Closes: #533 

## Description

- Removed extra code
- Removed breadcrumps~fixed head section of gallery page
- Fixed footer and aligned it similar to overall design of the page

## Screenshots

https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/100852245/19446a8b-bce2-4c12-aae5-72880ece44d8

## Checklist

- [X] My code adheres to the established style guidelines of the project.
- [X] I have included comments in areas that may be difficult to understand.
- [X] My changes have not introduced any new warnings.
- [X] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Viveksati5143** [comment]
@AshAman999 Please review and merge this pr.
I hope It will be level 2 as It multiple files had to be fixed to solve the issue.

**Review by Viveksati5143 — COMMENTED** [review]
Added recording of changes as well!!

**Comment by Viveksati5143** [comment]
@AshAman999 ??

**Review by AshAman999 — APPROVED** [review]

**Comment by Viveksati5143** [comment]
> @AshAman999 Please review and merge this pr. I hope It will be level 2 as multiple files had to be fixed to solve the issue.

Can you please merge it as well?

**Pull request merged**
