### PR TITLE
Events section modified

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have updated the events section.
Kindly review and merge ,also if you wanna any other changes then please inform me.

https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/132778037/1519edaa-4d8e-4d42-8564-472619532289

### CODE REVIEW

**Comment by SahityaRoy** [comment]
I can't see any improvement

**Comment by Pragati-3003** [comment]
> I can't see any improvement
Okie, I 'll add some more effects on this between 
I have added box - shadows and change some padding.

**Comment by SahityaRoy** [comment]
image

**Comment by Pragati-3003** [comment]
> image

resolved conflicts

**Comment by Pragati-3003** [comment]
@SahityaRoy  please add level number to the PR.

**Comment by Pragati-3003** [comment]
@SahityaRoy   , @AshAman999  please add level  number this PR.

**Pull request merged**
