### PR TITLE
updated file=Opensource Software Hacktober Fest

### PR DESCRIPTION
**Pull request by Bzsmrf**
This PR closes issue  #185 
before:
image
after:
image

### CODE REVIEW

**Comment by Bzsmrf** [comment]
we can now clone without conflict

**Comment by SyedImtiyaz-1** [comment]
Hello @Bzsmrf,
## I already solved this issue #144

**Comment by Bzsmrf** [comment]
@SyedImtiyaz-1  thanks for letting me know this I have made another changes I will mention the #185 issues is  solved by this PR

**Comment by SyedImtiyaz-1** [comment]
@Bzsmrf Okay, no issues.

**Comment by AshAman999** [comment]
@Bzsmrf 
I am tempted to merge this, can you please fix the merge conflict here and let me know!

**Pull request closed without merging**
