### PR TITLE
Create home.html

### PR DESCRIPTION
**Pull request by shubhams11-gt**
Updated some not functioning links of page in HTML also added link of college in home page address section

### CODE REVIEW

**Comment by SahityaRoy** [comment]
Please share the screenshots

**Comment by shubhams11-gt** [comment]
Screenshot 2022-10-16 180536

**Comment by shubhams11-gt** [comment]
Screenshot (385)

**Comment by shubhams11-gt** [comment]
these are some small changes 
I am working on dark mode right now
It needs a major change in code

**Pull request closed without merging**
