### PR TITLE
Aligned complete footer

### PR DESCRIPTION
**Pull request by Viveksati5143**
## Related Issue

Closes: #461 

## Description

Completely re-structured the footer of Events page that was completely messed up 
## Screenshots

image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by AshAman999** [comment]
It's already aligned right?

**Comment by Viveksati5143** [comment]
Nope

**Comment by Viveksati5143** [comment]
> It's already aligned right?

Please refer #461 or https://eduhubcommunity.tech/eventPage.html

**Comment by Viveksati5143** [comment]
> It's already aligned right?

So you reviewed it @AshAman999 ?

**Review by AshAman999 — APPROVED** [review]
LGTM !

**Comment by Viveksati5143** [comment]
> LGTM !

So, can you please merge it now?

**Comment by Viveksati5143** [comment]
Hey @AshAman999👋
Can you please assign me and add level 2 labels to this pr as well so that it gets reflected in the leaderboard?!?

**Pull request merged**
